import { Navbar } from "@/components/marketing/navbar";
import { Footer } from "@/components/marketing/footer";

const EFFECTIVE_DATE = "March 1, 2026";

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />

      <main className="flex-1 px-4 py-16">
        <div className="container mx-auto max-w-3xl">
          <h1 className="mb-2 text-3xl font-extrabold tracking-tight md:text-4xl">
            Terms of Service
          </h1>
          <p className="mb-10 text-sm text-muted-foreground">
            Effective date: {EFFECTIVE_DATE}
          </p>

          <div className="space-y-10 text-sm leading-relaxed text-muted-foreground">
            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing or using FitFusion (&quot;the Service&quot;), you
                agree to be bound by these Terms of Service. If you do not agree
                to these terms, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                2. Description of Service
              </h2>
              <p>
                FitFusion is an AI-powered fitness plan generator that produces
                personalized workout routines and nutrition plans based on user
                profile inputs (age, weight, height, gender, fitness goal, and
                training level). Plans are generated using automated AI
                workflows and are intended for informational and general wellness
                purposes only.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                3. Not Medical Advice
              </h2>
              <p>
                The fitness and nutrition plans generated by FitFusion are{" "}
                <strong className="text-foreground">
                  not medical advice
                </strong>
                . They are general wellness suggestions produced by an automated
                system. Always consult a qualified healthcare provider or
                licensed fitness professional before starting any new exercise or
                diet programme, particularly if you have pre-existing medical
                conditions, injuries, or other health concerns. FitFusion
                assumes no liability for any injury or adverse health outcome
                resulting from the use of generated plans.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                4. Account Registration
              </h2>
              <p>
                You must create an account to use the Service. You are
                responsible for maintaining the confidentiality of your account
                credentials and for all activity that occurs under your account.
                You agree to provide accurate and complete information during
                registration and to keep this information up to date.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                5. Credits and Payments
              </h2>
              <ul className="list-disc space-y-2 pl-5">
                <li>
                  New accounts receive 5 free credits upon registration. Each
                  fitness plan generation consumes 1 credit.
                </li>
                <li>
                  Paid plans (where available) are billed as described on the
                  Pricing page. All fees are non-refundable unless required by
                  applicable law.
                </li>
                <li>
                  FitFusion reserves the right to modify pricing at any time
                  with reasonable notice to existing subscribers.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                6. Acceptable Use
              </h2>
              <p className="mb-3">You agree not to:</p>
              <ul className="list-disc space-y-2 pl-5">
                <li>
                  Use the Service for any unlawful purpose or in violation of
                  these Terms.
                </li>
                <li>
                  Attempt to reverse-engineer, scrape, or otherwise extract data
                  from the Service in an unauthorised manner.
                </li>
                <li>
                  Use automated means to generate plans at scale beyond normal
                  personal use without a commercial agreement.
                </li>
                <li>
                  Share your account credentials with others or create accounts
                  for the purpose of circumventing credit limits.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                7. Intellectual Property
              </h2>
              <p>
                The FitFusion brand, website, and underlying software are owned
                by FitFusion and protected by applicable intellectual property
                laws. Fitness plans generated for you are for your personal use
                only and may not be resold or redistributed commercially without
                prior written permission.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                8. Disclaimer of Warranties
              </h2>
              <p>
                The Service is provided &quot;as is&quot; and &quot;as
                available&quot; without warranties of any kind, either express
                or implied. FitFusion does not warrant that the Service will be
                uninterrupted, error-free, or that the AI-generated plans will
                meet your specific fitness goals.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                9. Limitation of Liability
              </h2>
              <p>
                To the maximum extent permitted by law, FitFusion shall not be
                liable for any indirect, incidental, special, consequential, or
                punitive damages arising from your use of the Service, including
                but not limited to personal injury, loss of data, or financial
                loss.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                10. Termination
              </h2>
              <p>
                FitFusion reserves the right to suspend or terminate your
                account at any time if you violate these Terms or engage in
                conduct that is harmful to other users or the Service. You may
                also delete your account at any time by contacting us.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                11. Changes to These Terms
              </h2>
              <p>
                We may update these Terms from time to time. Continued use of
                the Service after changes are posted constitutes your acceptance
                of the revised Terms. We will update the effective date at the
                top of this page when changes are made.
              </p>
            </section>

            <section>
              <h2 className="mb-3 text-base font-semibold text-foreground">
                12. Contact
              </h2>
              <p>
                If you have questions about these Terms, please reach out via
                the Contact form in the footer.
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
